### PR TITLE
Fix skip link focus issues

### PR DESCRIPTION
**Pull request by aevanson**
Issues: #154, #192

- Fixes link focus issues with accordions
- Fixes general skip link focus issues
- Removes bug where accordion skip links were causing issues with links
that were only pointing to '#'

### CODE REVIEW

**Comment by aevanson** [comment]
Don't merge yet — I need to make a slight tweak to fix links under components that are added after the global script fires.

- [ ] Fix race condition

**Comment by aevanson** [comment]
@liskulic I'll double-check. They were working before. Hopefully this code change doesn't break them...I'll confirm

**Comment by aevanson** [comment]
Hey @liskulic Lisa, I'm seeing the skip links in Safari without issue:

image

The only thing I noticed is that in Safari, it tends to scroll the page to 'just below' the link rather than just above (so it just off page). One solution for this is to add `event.preventDefault()` to the skip link click listener. I can add this in if think it's better without the scrolling. I tested it a amount, and if the scrolling is disabled with `preventDefault()`, the page will still scroll if the focus moves to an element that's not currently in view. CC: @brianelton @alisonrae

**Comment by liskulic** [comment]
@aevanson, that works for me. Thanks.

**Pull request merged**
